In [1]:
import torch

In [2]:
x = torch.tensor(4.0, requires_grad = True) #requrire_grad used for back propagation
x

tensor(4., requires_grad=True)

In [9]:
y = x**2

In [10]:
#back propagation  y = 2x
y.backward()

In [11]:
print(x.grad)

tensor(8.)


In [13]:
lst = [[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]
z = torch.tensor(lst,requires_grad=True)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [ ]:
#y = x^3 + x^2
#dy/dx = 3x^2 + 2x
pred_val = z**3+ z**2
pred_val

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [17]:
a = pred_val.sum()
a

tensor(2310., grad_fn=<SumBackward0>)

In [19]:
a.backward()

In [ ]:
#dy/dx = 3x^2 + 2x
z.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])