In [1]:
import torch
import numpy as np


In [2]:
torch.__version__

'2.7.1+cu118'

In [3]:
import numpy as np
arr = [1,2,3,4]
arr = np.array(arr)
type(arr)

numpy.ndarray

In [4]:
tensors = torch.from_numpy(arr)
tensors, type(tensors)

(tensor([1, 2, 3, 4]), torch.Tensor)

In [5]:
tensors[:3]

tensor([1, 2, 3])

In [6]:
tensors[3] = 123
arr

array([  1,   2,   3, 123])

In [8]:
arr2 = np.array([1,2,3,4])
tensor2 = torch.tensor(arr2)
tensor2[3] = 45
arr2, tensor2

(array([1, 2, 3, 4]), tensor([ 1,  2,  3, 45]))

In [ ]:
zero = torch.zeros(2,3,dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [11]:
ones = torch.ones(3,3, dtype= torch.float32)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
a = torch.tensor([1,2,3,4] , dtype = torch.float)
b = torch.tensor([23,345,54,65], dtype = torch.float)

torch.add(a,b), torch.sub(a,b)

(tensor([ 24., 347.,  57.,  69.]), tensor([ -22., -343.,  -51.,  -61.]))

In [10]:
a+b

tensor([ 24., 347.,  57.,  69.])

In [12]:
c = torch.zeros(4)

torch.add(a,b, out=c)
c

tensor([ 24., 347.,  57.,  69.])

In [14]:
torch.add(a,b).sum()

tensor(497.)

In [5]:
arr_2d = torch.tensor(np.arange(1,16).reshape(5,3))
arr_2d, type(arr_2d)

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]),
 torch.Tensor)

In [6]:
arr_2d[1]

tensor([4, 5, 6])

In [8]:
arr_2d[1,1:]

tensor([5, 6])

In [13]:
#dot and multi operation

a.mul(b)

tensor([ 23., 690., 162., 260.])

In [16]:
a,b

(tensor([1., 2., 3., 4.]), tensor([ 23., 345.,  54.,  65.]))

In [17]:
a.dot(b)
#1*23+2*345+3*54+4*64

tensor(1135.)

In [ ]:
#matrix multiplication
x = torch.tensor(np.arange(1,10).reshape(3,3), dtype = torch.int32)
y = torch.tensor(np.arange(21,30).reshape(3,3), dtype = torch.int32)
x,y

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]], dtype=torch.int32),
 tensor([[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]], dtype=torch.int32))

In [ ]:
x.mul(y)    #normul multiplication

tensor([[ 21,  44,  69],
        [ 96, 125, 156],
        [189, 224, 261]], dtype=torch.int32)

In [6]:
x.matmul(y)

tensor([[150, 156, 162],
        [366, 381, 396],
        [582, 606, 630]], dtype=torch.int32)

In [8]:
torch.mm(x,y)

tensor([[150, 156, 162],
        [366, 381, 396],
        [582, 606, 630]], dtype=torch.int32)

In [9]:
x@y

tensor([[150, 156, 162],
        [366, 381, 396],
        [582, 606, 630]], dtype=torch.int32)